#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$dotenv = new \Dotenv\Dotenv(__DIR__);
$dotenv->load();

require __DIR__ . '/../vendor/autoload.php';

$object = new \JimChen\MobileRealNameVerify\MobileRealNameVerify([
    'appkey' => getenv('TEST_APPKEY')
]);

try {
    var_dump($object->verify(getenv('TEST_MOBILE'), $_ENV['TEST_REAL_NAME'], getenv('TEST_ID_CARD')));
} catch (\Exception $e) {
    var_dump($e->getCode());
    var_dump($e->getMessage());
}
